version: "3.7"

services:
  backend:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    restart: "always"
    command: "uvicorn main:app --reload --host 0.0.0.0"
    image: backend
    ports:
      - "8000:8000"
    env_file: ../.env
    volumes:
      - "../src:${APP_HOME}/src"

  mongodb:
    image: mongo:4.4.4-bionic
    ports:
      - "27017:27017"
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${PASSWORD}
    volumes:
      - ../mongodb:/data/db
